const API = {}
API.GET_SUP_LIST = '/prd/getSupList'
API.GET_BRAND_LIST = '/prd/brand/getBrandList'
API.GET_MDID_LIST = '/prd/md/getMdIdList'
API.GET_CMM_CODE_LIST = '/cmm/getCmmCodeList'
API.GET_PRD_CLS_M_LIST = '/prdClsM/getPrdClsMList'
API.GET_SUB_SUP_LIST = '/prd/sups/getSubSupList'
API.GET_PRD_CLS_UDA_CD_ALL_LIST = '/prdClsM/getPrdClsUdaCDAllList'
API.GET_DIFF_PRD_CTGR_SHOP = '/prd/getDiffPrdCtgrShop'
API.GET_ETC_LRG_SHOP_LIST = '/prd/ecShop/getEtcLrgShopList'
API.GET_ETC_SUB_SHOP_LIST = '/prd/ecShop/getEtcSubShopList'
API.GET_PRD_REPORT_MST_INFO = '/prd/getPrdReportMstInfo'
API.GET_EC_SHOP_LIST = '/prd/ecShop/getEcShopList'
API.GET_PRD_CNTNT_LIST = '/prd/cntnt/getPrdCntntList'
API.GET_PRD_CLS_BY_BASE_VAL_LIST = '/prdClsM/getPrdClsByBaseValList'
API.GET_PRD_BASE = '/prd/getPrdBase'
API.SET_PRD_BASE = '/prd/setPrdBase'
API.GET_PRD_LIST_TO = '/prd/getPrdListto'
API.GET_MD_EMP_LIST = '/prd/md/getMdEmpList'
API.GET_PRD_LIST = '/prd/popup/getPrdList'
API.SAVE_CNTNT_LIST = '/prd/cntnt/saveCntntList'
API.MODIFY_PUB_IMG_CHG = '/prd/cntnt/modifyPubImgChg'
API.REMOVE_CNTNT_LIST = '/prd/cntnt/removeCntntList'
API.ATTACHMENT = '/cmm/attachment'
API.ADD_PRD_BANNER_IMG_LIST = '/prd/cntnt/addPrdBnnrImgList'
API.REMOVE_BANNER_IMG_LIST = '/prd/cntnt/removePrdBnnrImgList'
API.GET_ITEM_M_LIST = '/prd/item/getItemMList'
API.GET_QA_REQ_ITM_LIST_NEW = '/prd/descd/getQaReqItmList?prdCd={0}'
API.GET_PRD_ATTR_PRD_LIST = '/prd/attr/getPrdAttrPrdList'

API.GET_EC_CNTRB_PROFIT = '/prd/profitEc/getEcCntrbProfit'
API.GET_EC_CNTRB_PROFIT_SIMUL = '/prd/profitEc/getEcCntrbProfitSimul'
API.GET_AS_RTP_STD = '/prdClsM/getAsRtpStd'
API.MODIFY_AS_RTP_STD_LIST = '/prdClsM/modifyAsRtpStdList'
API.GET_PRD_GOV_PUBLS_LIST_NEW = '/prd/descd/getPrdGovPublsListNew'
API.GET_PRD_DESCD_GENRL_D_LIST_NEW = '/prd/descd/getPrdDescdGenrlDListNew'
API.GET_PRD_LIST_TTO_DTL = '/prd/attr/getPrdListtoDtl'
API.GET_PRD_STATUS = '/prd/getPrdStatus'

API.REMOVE_PRD_DESCD_GENRL_D_LIST = '/prd/descd/removePrdDescdGenrlDList'
API.GET_PRD_DESCD_REF = '/prd/descd/getPrdDescdRef?prdCd={0}'

API.GET_PRC_PMO_WEB_LIST = '/prd/prdPrcPmoWebList/getPrcPmoWeb'
API.GET_PRD_PMO_WEB_GIFT_LIST = '/prd/pmo/getGftList'
API.GET_PRD_PMO_WEB_ATTR_PRD_PMO_GIFT_LIST = '/prd/pmo/getAttrPrdPmoGftList'
API.GET_PRD_PMO_WEB__PMO_WEB_LIST = 'prd/prdPmoWeb/getPmoWebList'
API.GET_PRD_PMO_WEB_ATTR_SALE_ST_LIST = '/prd/getPrdAttrSaleStList'
API.GET_PRD_PMO_WEB_LIST = '/prd/prdPmoWeb/getPrdPmoWeb'

API.GET_PRC_PMO_WEB_GET_SUMMARY_INFO = '/prd/prdPmoWeb/getPrdPrcSummary'

API.SAVE_PRD_UDA_D = '/prd/uda/savePrdUdaD'
API.GET_PRD_CLS_UDA_LIST = '/prdClsUda/getPrdClsList'
API.GET_PRD_SALE_PRO_AGREE_DOC_BROWS = '/prd/getPrdSaleProAgreeDocBrows'
API.GET_MODIFY_AUTH_PMO = '/prd/prdPrcPmoWebList/getModifyAuthPmo'
API.ADD_PRD_PMO = '/prd/pmo/addPrdPmo'
API.SAVE_PRD_PMO = 'prd/prdPmo/savePrdPmo'

API.GET_PRD_GFT_SALE_PRO_AGREE_DOC_BROWS = '/prd/getPrdGftSaleProAgreeDocBrows'
API.GET_SUP_UDA_DTL_INFO = '/supUdaMng/getSupUdaDtlInfo'
API.GET_SUP_UDA_DTL_LIST = '/prd/sups/getSupUdaDtlList'

API.GET_PRD_CHG_HIST_LIST = '/prdChg/getPrdChgHistList'
API.GET_ATTR_PRD_CHG_HIST_LIST = '/prd/attr/getAttrPrdChgHistList'
API.GET_ATTR_PRD_HIST_LIST = '/prd/attr/getAttrPrdOrdPsblQtyChgHistList'
API.SAVE_PRD_PRC_LIST = '/prd/prdPrcPmoWebList/savePrdPrcList'
API.GET_BROAD_AGREE_DOC_INFO = '/prd/getBroadAgreeDocInfo'
API.GET_PRD_CHANL_CHG_HIST_LIST = '/prdChg/getPrdChanlChgHistList'
API.GET_PRD_MY_LIST = '/cmm/md/getPrdMyList?userId={0}'
API.SAVE_PRD_MY_LIST = '/cmm/md/savePrdMyList'
API.GET_MULTICODE_LIST = '/prd/multiCdQryPopup/getMultiCdList'

API.GET_MY_SCREN_CMPOS_LIST = '/cmm/getMyScrenCmposList'
API.SAVE_ITM_SEQ_AD_JST_LIST = '/cmm/saveItmSeqAdjstList'

API.GET_PRD_ATTR_VAL_C_LIST = '/prd/prdClsAttrVal/getPrdAttrValCList'
API.GET_PRD_GBN_BY_QRY_POPUP_LIST = '/prd/getPrdGbnByQryPopupList'

API.GET_SUP_COVER_CONT = '/ods/getSupCoverCont'
API.GET_BOARD_SUPLY_PLAN_GFT_END_CHK = '/atp/getBroadSuplyPlanGftEndChk'
API.GET_CPN_LIST_P = '/cpn/getCpnListP'
API.GET_PRD_INFO = '/prd/getPrdInfo?prdCd={0}'
API.GET_PRD_REQ_INFO = '/prd/prdAgreeDoc/getPrdReqInfo?prdCd={0}' // Chance
API.GET_PRD_INFO_GENRL = '/prd/getPrdInfoGenrl/{0}'
API.CREATE_PRD_SALE_REQ_REG_D = '/prd/createPrdSaleReqRegD'
API.SAVE_PRCH = '/prd/savePrcH'
API.GET_PRC_LIST_BY_PRDCD = '/prd/prc/getPrcListByPrdCd'
API.GET_PRD_PRC_PMO_LIST =
  '/prd/prdPmoWeb/getPrdPrcPmoList?prdCd={0}&validStrDtm={1}'
API.GET_PRD_CLS_UDA_CD_LIST = '/prdClsM/getPrdClsUdaCDList'
API.GET_PROFIT_PRD = '/prd/profit/getProfitPrd'
API.GET_PMO_REQ_INFO = '/prd/pmoreq/getPmoReqInfo'
API.GET_PRD_INFO_WEB = '/prd/prdPrcPmoWebList/getPrdInfoWeb'
API.GET_PRD_PROFIT_MINUS_REQ_CNT = '/prd/minusProfit/getPrdProfitMinusReqCnt'
// API.GET_PROFIT_PRD = "/prd/profit/getProfitPrd"; // Chance
API.GET_CURR_PGMYN = '/prd/prdPrcPmoWebList/getCurrPgmYn'
API.GET_PRD_ALWYS_DEAL_FORM_DESC_1 = '/prd/deal/getPrdAlwysDealFormDesc'
API.GET_SUP_PRD_PMO_CONT_INFO = '/ods/getSupPrdPmoContInfo'
API.SAVE_PRD_PMO_REG_REQ_D = '/prd/pmoreq/savePrdPmoRegReqD'
API.CREATE_PRD_SALEPRO_AGREE_DOC_INFO = '/prd/createPrdSaleproAgreeDocInfo'
API.GET_CURR_PGM_YN_1 = '/prd/prdPrcPmoWebList/getCurrPgmYn?prdCd={0}'
API.GET_FUTUR_PGM_INFO = '/dmc/getFuturPgmInfo?prdCd={0}'
API.GET_PRD_ALWYS_DEAL_FORM_DESC = '/prd/deal/getPrdAlwysDealFormDesc?prdCd={0}'
API.SET_PRD_UPDATE = '/prd/setPrdUpdate'
API.GET_ACCM_GIV_LIMIT_RATE_CODE = '/ord/getAccmGivLimitRtCd'
API.GET_PRD_COPY_LIST_TO = '/prd/getPrdCopyListto'
API.GET_PRD_BROAD_HISTORY = '/prd/broad/getPrdBroadHistory'
API.GET_PRD_REQ_INFO_1 = '/prd/prdAgreeDoc/getPrdReqInfo'

export default API
